In [5]:
print("hello world")

hello world

In [6]:
INPUT_FILE_PATH = "netflix_titles.csv"
OUTPUT_FILE_PATH = "netflix_titles_py.csv"

In [7]:
with open (INPUT_FILE_PATH, "r", encoding="utf-8" ) as f:
    for line in f:
        print(line)
        break

duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id

In [8]:
with open (INPUT_FILE_PATH, "r", encoding="utf-8") as f:
    pass

In [9]:

import pandas as pd

In [10]:
df_csv = pd.read_csv(INPUT_FILE_PATH)

In [24]:
from datetime import datetime

In [14]:
df_csv["fecupdate"] = datetime.now()

In [16]:
df_csv.head(2)

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id,fecupdate
0,90,NaN,Movie,Norm of the North: King Sized Adventure,2019-09-09 00:00:00,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0,2026-09-19 11:19:30.622697
1,94,NaN,Movie,Jandino: Whatever it Takes,2016-09-09 00:00:00,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0,2026-09-19 11:19:30.622697

In [22]:
import pytz 
peru_tz = pytz.timezone("America/Lima")

In [23]:
df_csv["fecupdate"] = datetime.now(peru_ztz)

In [25]:
df_csv.head(2)

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id,fecupdate
0,90,NaN,Movie,Norm of the North: King Sized Adventure,2019-09-09 00:00:00,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0,2026-09-19 11:24:27.499985-05:00
1,94,NaN,Movie,Jandino: Whatever it Takes,2016-09-09 00:00:00,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0,2026-09-19 11:24:27.499985-05:00

In [ ]:
# INGENIERIA DE DATOS

""" 
1. DEFINIER PARÁMETROS
2. CREAR CARPETAS
3. VALIDAR EXISTENCIA DE ARCHIVOS
4. LIMPIAR DIRECTORIOS
5. LEER Y GUARDAR DATOS
6. MANEJO DE LOGGINGS

"""

In [26]:
# INTERACTUANDO CON EL SISTEMA OPERATIVO 

import os

In [27]:
import shutil

In [28]:
os.getcwd()

'c:\\Users\\Lenovo\\Desktop\\DATA ENGENIERING'

In [29]:
os.listdir()

['.claude',
 '.venv',
 '03a_Laboratorio01.pdf',
 '1_python_introduction.ipynb',
 '2a_python_introduction_main.ipynb',
 '2_python_os.ipynb',
 '3_netflix_titles_csv_basic.ipynb',
 '4_python_logging.ipynb',
 '5_netflix_titles_csv_lab01.ipynb',
 '6_netflix_titles_xlsx.ipynb',
 'LAB01.ipynb',
 'netflix_titles.csv',
 'netflix_titles.xlsx',
 'SETUP-PROYECTO.md']

In [30]:
os.path.join(os.getcwd(INPUT_FILE_PATH))

TypeError: nt.getcwd() takes no arguments (1 given)

In [31]:
os.mkdir("test.py")

In [33]:
os.makedirs("test1/test2")

In [34]:
os.rename("test.py", "test")

In [35]:
os.path.exists("test")

True

In [36]:
# MOVER CARPETAS

In [40]:
file_path = "test1"

In [43]:
target_path = "test"

In [44]:
shutil.move(file_path, target_path)

FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

In [45]:
os.rmdir("test")

In [46]:
shutil.rmtree("test")

FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'test'

In [47]:
# Trabajando con Programas

In [ ]:
# SETUP

In [7]:
import os
import shutil
import pandas as pd

PATH_OUTPUTS = "datalake"
INPUT_DIR = os.path.join(PATH_OUTPUTS, 'datalake_inputs')
OUTPUT_DIR = os.path.join(PATH_OUTPUTS, 'datalake_outputs')
GITHUB_ROOT_PATH = 'https://raw.githubusercontent.com/AngelTintaya/datasets/refs/heads/main/'
INPUT_FILE_PATH = os.path.join(GITHUB_ROOT_PATH, 'netflix_titles.csv')
OUTPUT_FILE_PATH = os.path.join(INPUT_DIR, 'netflix_titles.csv')

if os.path.exists(PATH_OUTPUTS):
  shutil.rmtree(PATH_OUTPUTS)

os.makedirs(PATH_OUTPUTS, exist_ok=True)
os.makedirs(INPUT_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)


pd.read_csv(INPUT_FILE_PATH).to_csv(OUTPUT_FILE_PATH, index=False)

del PATH_OUTPUTS, INPUT_DIR, OUTPUT_DIR, GITHUB_ROOT_PATH, INPUT_FILE_PATH, OUTPUT_FILE_PATH

In [8]:
ROOT_DIR = 'datalake'
INPUT_DIR = os.path.join(ROOT_DIR, 'datalake_inputs')
OUTPUT_DIR = os.path.join(ROOT_DIR, 'datalake_outputs')
INPUT_FILE_PATH = os.path.join(INPUT_DIR, 'netflix_titles.csv')
OUTPUT_FILE_PATH = os.path.join(OUTPUT_DIR, 'netflix_titles.csv')

In [ ]:
def validar_existencia_archivo(path):
  pass

In [9]:
def validar_existencia_archivo(path):
  """Valida si el archivo existe."""
  if not os.path.exists(path):
    print(f'El archivo no existe: {path}')
    return False
  
  return True

In [10]:
path = "datalake"

for item in os.listdir(path):
    ruta = os.path.join(path,item)
    print(item)
    print(ruta)

datalake_inputs
datalake\datalake_inputs
datalake_outputs
datalake\datalake_outputs

In [5]:
def limpiar_directorio():
  pass

In [12]:
def limpiar_directorio(path):
  """Elimina todos los archivos y carpetas dentro de un directorio."""
  for item in os.listdir(path):
    ruta = os.path.join(path, item)

    if os.path.isfile(ruta):
      os.remove(ruta)
    elif os.path.isdir(ruta):
      shutil.rmtree(ruta)
  
  print(f"Directorio limpiado: {path}")

In [25]:
import time

In [26]:
def leer_y_guardar_csv(file_path, output_path):
  """Mueve el archivo CSV de una ruta a otra."""
  df_csv = pd.read_csv(file_path)
  df_csv.to_csv(output_path, index=False)

  print(f"Guardado: {output_path}")

In [27]:
def main():
  print(f"Directorio Input: {INPUT_DIR}")
  print(f"Directorio Output: {OUTPUT_DIR}")
  print(f"Archivo Input: {INPUT_FILE_PATH}")
  print(f"Archivo Output: {OUTPUT_FILE_PATH}")

  if not validar_existencia_archivo(INPUT_FILE_PATH):
    return
  
  limpiar_directorio(OUTPUT_DIR)

  time.sleep(5)

  leer_y_guardar_csv(INPUT_FILE_PATH, OUTPUT_FILE_PATH)

  print("Proceso finalizado con éxito.")

In [28]:
if __name__ == "__main__":
    main()

Directorio Input: datalake\datalake_inputs
Directorio Output: datalake\datalake_outputs
Archivo Input: datalake\datalake_inputs\netflix_titles.csv
Archivo Output: datalake\datalake_outputs\netflix_titles.csv
Directorio limpiado: datalake\datalake_outputs
Guardado: datalake\datalake_outputs\netflix_titles.csv
Proceso finalizado con éxito.